name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: List Available Simulators (Debug Step)
        run: xcrun simctl list devices

      - name: Build for Testing
        run: |
          xcodebuild build-for-testing \
            -scheme Recipes \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=18.2'

      - name: Run Tests Without Building
        run: |
          xcodebuild test-without-building \
             -scheme Recipes \
             -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=18.2' \
             -only-testing:RecipesTests \
             -enableCodeCoverage YES
